services:
  parkmanager-postgres:
    image: postgres:17
    container_name: parkmanager_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 10

  parkmanager-service:
    container_name: parkmanager_service
    build:
      context: .
      dockerfile: ParkManager-Service/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=parkmanager-postgres
      - DB_PORT=5432
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=Host=parkmanager-postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      parkmanager-postgres:
        condition: service_healthy
    volumes:
      - ./ParkManager-Service:/src/ParkManager-Service
      - ~/.nuget/packages:/root/.nuget/packages:ro

volumes:
  postgres_data: