FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./

RUN npm ci

FROM builder AS prod

COPY . .

RUN npm run build

FROM nginx:stable-alpine

# Remove configuração padrão
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos gerados para a pasta pública do nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia um nginx.conf customizado
COPY nginx.conf /etc/nginx/nginx.conf

# Expondo a porta padrão HTTP
EXPOSE 80

# Comando padrão
CMD ["nginx", "-g", "daemon off;"]