FROM node:20-alpine AS build
WORKDIR /app

COPY ParkManager-Frontend/package*.json ./

RUN npm ci

COPY ParkManager-Frontend ./
RUN npm run build

FROM nginx:stable-alpine

# Remove configuração padrão
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos gerados para a pasta pública do nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copia um nginx.conf customizado
COPY ParkManager-Frontend/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]