// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkManager_Service.Data;

#nullable disable

namespace ParkManager_Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702174255_SchemaMigration")]
    partial class SchemaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ParkManager_Service.Models.Acesso", b =>
                {
                    b.Property<int>("IdAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_acesso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAcesso"));

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_entrada");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_saida");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstacionamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_estacionamento");

                    b.Property<int?>("IdEvento")
                        .HasColumnType("integer")
                        .HasColumnName("id_evento");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa_veiculo");

                    b.Property<int?>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal?>("ValorAcesso")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("valor_acesso");

                    b.HasKey("IdAcesso");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstacionamento");

                    b.HasIndex("IdEvento");

                    b.ToTable("ACESSO");
                });

            modelBuilder.Entity("ParkManager_Service.Models.Estacionamento", b =>
                {
                    b.Property<int>("IdEstacionamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estacionamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstacionamento"));

                    b.Property<decimal>("AdicionalNoturno")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("adicional_noturno");

                    b.Property<decimal>("DescontoHora")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("desconto_hora");

                    b.Property<decimal>("Faturamento")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("faturamento");

                    b.Property<TimeSpan?>("HoraAbertura")
                        .HasColumnType("interval")
                        .HasColumnName("hora_abertura");

                    b.Property<TimeSpan?>("HoraFechamento")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fechamento");

                    b.Property<string>("IdGerente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_gerente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeContratante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_contratante");

                    b.Property<decimal>("RetornoContratante")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("retorno_contratante");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("VagasOcupadas")
                        .HasColumnType("integer")
                        .HasColumnName("vagas_ocupadas");

                    b.Property<int>("VagasTotais")
                        .HasColumnType("integer")
                        .HasColumnName("vagas_totais");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("valor_diaria");

                    b.Property<decimal>("ValorFracao")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("valor_fracao");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("valor_mensal");

                    b.HasKey("IdEstacionamento");

                    b.HasIndex("IdGerente");

                    b.ToTable("ESTACIONAMENTO");
                });

            modelBuilder.Entity("ParkManager_Service.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_evento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvento"));

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<int>("IdEstacionamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_estacionamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<decimal>("ValorEvento")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("valor_evento");

                    b.HasKey("IdEvento");

                    b.HasIndex("IdEstacionamento");

                    b.ToTable("EVENTO");
                });

            modelBuilder.Entity("ParkManager_Service.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ParkManager_Service.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ParkManager_Service.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkManager_Service.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ParkManager_Service.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParkManager_Service.Models.Acesso", b =>
                {
                    b.HasOne("ParkManager_Service.Models.Usuario", "Cliente")
                        .WithMany("Acessos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkManager_Service.Models.Estacionamento", "Estacionamento")
                        .WithMany("Acessos")
                        .HasForeignKey("IdEstacionamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkManager_Service.Models.Evento", "Evento")
                        .WithMany("Acessos")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Estacionamento");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("ParkManager_Service.Models.Estacionamento", b =>
                {
                    b.HasOne("ParkManager_Service.Models.Usuario", "Gerente")
                        .WithMany("EstacionamentosGerenciados")
                        .HasForeignKey("IdGerente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("ParkManager_Service.Models.Evento", b =>
                {
                    b.HasOne("ParkManager_Service.Models.Estacionamento", "Estacionamento")
                        .WithMany("Eventos")
                        .HasForeignKey("IdEstacionamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamento");
                });

            modelBuilder.Entity("ParkManager_Service.Models.Estacionamento", b =>
                {
                    b.Navigation("Acessos");

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("ParkManager_Service.Models.Evento", b =>
                {
                    b.Navigation("Acessos");
                });

            modelBuilder.Entity("ParkManager_Service.Models.Usuario", b =>
                {
                    b.Navigation("Acessos");

                    b.Navigation("EstacionamentosGerenciados");
                });
#pragma warning restore 612, 618
        }
    }
}
