name: Lint and Test ParkManager - Pipeline

on:
  push:
    branches:
      - main
      - ci_cd_test
  pull_request:
    branches:
      - main
      - ci_cd_test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Run dotnet linter
        run: |
          dotnet restore ParkManager-Service/ParkManager-Service.csproj
          dotnet format ParkManager-Service/ParkManager-Service.csproj --verify-no-changes --verbosity d --no-restore

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres_ci
          POSTGRES_PASSWORD: postgres_ci_pass
          POSTGRES_DB: ParkManager_CI_Tests
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres_ci -d ParkManager_CI_Tests"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres_ci; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef
        env:
          PATH: ${{ env.PATH }}:/home/runner/.dotnet/tools

      - name: Apply Database Migrations
        env:
          ASPNETCORE_ENVIRONMENT: Test
          PATH: ${{ env.PATH }}:/home/runner/.dotnet/tools
          ConnectionStrings__DefaultConnection: Host=localhost;Port=5432;Database=ParkManager_CI_Tests;Username=postgres_ci;Password=postgres_ci_pass
        run: |
          dotnet ef database update --project ParkManager-Service

      - name: Run tests
        env:
          ASPNETCORE_ENVIRONMENT: Test
          POSTGRES_USER: postgres_ci
          POSTGRES_PASSWORD: postgres_ci_pass
          POSTGRES_DB: ParkManager_CI_Tests
          DB_HOST: localhost
          DB_PORT: 5432
          ConnectionStrings__DefaultConnection: Host=localhost;Port=5432;Database=ParkManager_CI_Tests;Username=postgres_ci;Password=postgres_ci_pass
        run: |
          dotnet restore ParkManager-Service/ParkManager-Service.csproj
          dotnet test ParkManager-Service/ParkManager-Service.csproj -l "console;verbosity=normal" --no-restore
